# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: reau.ca
lang: fr
author:
  name: Geoffray RÉAU
  email: contact@reau.ca

description: >- # this means to ignore newlines until "baseurl:"
  Geoffray RÉAU is a confirmed Technology Project Management Specialist with 19+ years of experience in Infrastructure Technology.
  From Design to Delivery and beyond, his main objective is to foster trustful partnerships while delivering the most relevant solutions to the technology challenges he is presented with.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.reau.ca" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-625TCRJR1K

show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
feed:
  categories:
    - Artificial Intelligence
    - IT Network
    - IT Security
    - Network Design
    - Work Tips
permalink: /:year/:month/:day/:title:output_ext

# Minima theme settings
minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto
#
#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
  nav_pages:
    - categories.markdown
    - about.markdown
#
#   Set to `true` to show excerpts on the homepage.
  show_excerpts: true
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
  date_format: "%b-%d-%Y"
#
#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
  social_links:
    - title: Geoffray Réau at GitHub
      icon: github
      url: "https://github.com/rfc2784"
    - title: Geoffray Réau at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/greau/"
    - title: Geoffray Réau at BlueSky
      icon: bluesky
      url: "https://bsky.app/profile/tiog.eu.org"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.
  hide_site_feed_link: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
